uploads = []
generated = []

[[outputs]]
id = "qTT4BCNsfxu2QpDPjjnqJ"
uri = "file://LiftFlow-1.7.3-build20.zip"
type = "unspecified"
title = "LiftFlow-1.7.3-build20.zip"

[[outputs]]
id = "xbHA5jiW-kqy4iRl0VvCF"
uri = "file://LiftFlow-1.7.4-build20.zip"
type = "unspecified"
title = "LiftFlow-1.7.4-build20.zip"

[[outputs]]
id = "oCk29GvhIVcnMA5l-LXl-"
uri = "file://LiftFlow-1.7.5-build21.zip"
type = "unspecified"
title = "LiftFlow-1.7.5-build21.zip"

[[outputs]]
id = "4KEs2x7xI-zU8eLyI0qKC"
uri = "file://LiftFlow.zip"
type = "unspecified"
title = "LiftFlow-1.7.5-build21.zip"
