// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/liftflow-dark/Dashboard.tsx": () => import("../components/mockups/liftflow-dark/Dashboard.tsx"),
  "./components/mockups/liftflow-dark/Progress.tsx": () => import("../components/mockups/liftflow-dark/Progress.tsx")
};
